### ISSUE TITLE
Add shutdown to cross-chain-hub e2e test

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/fiber#126]
> While trying to demo the functionality of cross chain hub, I also added a few requests to close the channels in both lightning network and fiber network. Can you also add these to current PR? I think it would make the e2e test more complete. Here is my additional bruno files. https://github.com/nervosnetwork/cfn-node/tree/afbfc1e5a1c2dc2f900dae57f00ba1ac86f4927c/tests/bruno/e2e/cross-chain-hub

_Originally posted by @contrun in https://github.com/nervosnetwork/cfn-node/issues/46#issuecomment-2204944558_

**Comment by contrun** [comment]
Pull request is here https://github.com/doitian/cfn-node/pull/2

**Comment by doitian** [comment]
Closed by https://github.com/doitian/cfn-node/pull/2
