### ISSUE TITLE
Save remote commitment numbers whenever a new local commitment transaction is committed

### ISSUE THREAD

**Issue by contrun** [nervosnetwork/fiber#132]
When we build and partially sign a commitment transaction, we are using a snapshot of the channel state. There are a few required parameters that need saving in order to construct this commitment transaction later.

- The direct payment keys for the counter party.
- The list of all tlcs that should be included in this commitment transaction. 

Since the direct payment keys are rotated each time the remote commitment number updates and the list of TLCs to be included depends on the remote commitment number. We need to save the remote commitment number in order to reconstruct this local commitment transaction later.

**Comment by chenyukang** [comment]
currently, we store the latest commitment transaction.
what's is the intention to reconstruct an older commitment transaction? I mean the older one than the latest one.

**Comment by contrun** [comment]
I should have said older commitment transaction parameters (but not commitment transaction per se). Commitment transaction witnesses are required for revoke old transactions. Imagine that we signed nth local transactions in total, and the adversary broadcast the mth ($0 \leq m \leq n$) to the network, then we need to reconstruct the witnesses, which depend on the remote commitment number.

**Comment by contrun** [comment]
I currently used the wrong public key to construct the commitment transaction. We shouldn't need remote commitment number to build local commitment transaction witnesses. I fixed this in https://github.com/nervosnetwork/cfn-node/pull/133/commits/f24ad0856f98749684da0e7d542f97d0833a4df0
