### ISSUE TITLE
Ensure generating unique channel seed

### ISSUE THREAD

**Issue by contrun** [nervosnetwork/fiber#175]
https://github.com/nervosnetwork/cfn-node/blob/4fd16cc6194070947d4fe0555ff52ac46ccf4df3/src/fiber/network.rs#L2025-L2035

We may generate the same seed (used to create various secrets for the channel) here because the length of  `self.channels` may decrease on channel closure. We need to ensure the `channel_user_id` is always monotonically increasing here.

**Comment by quake** [comment]
the system time is part of entropy, I don't think it will generate same seed even channels len decreasing.

**Comment by contrun** [comment]
You're right. Entropy is updated every time we generate a new seed. So it doesn't really matter if we used the same `channel_user_id`.
