### ISSUE TITLE
Use hex string to deserialize numbers in RPC

### ISSUE THREAD

**Issue by contrun** [nervosnetwork/fiber#18]
We shouldn't use JSON number in RPC as JSON number can't represent large u128 values (not even u64 numbers https://github.com/serde-rs/json/issues/329). We need to use strings like `"0x42424242424242424242424242424242"`. See also [`ckb_jsonrpc_types::Uint64`](https://docs.rs/ckb-jsonrpc-types/latest/ckb_jsonrpc_types/type.Uint64.html) for how ckb processes numbers in rpc.

**Comment by chenyukang** [comment]
This is fixed after the RPC refactor finished.
