### ISSUE TITLE
[send_payment]  have channel but return Channel not found error

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/fiber#247]
```
while true 
  1. open_channel 
  2. wait channel ready 
  3. invoice
  4. send_payment
  5. close_channel
```
return   2024-10-18T09:38:16.833441Z ERROR fnn::fiber::network: Failed to send message to channel actor: channel Hash256(0x6b1bb599af3f72639881100f634f0195ed333f59a0e9f3de6ac2519179202689) not found, message: Event(ClosingTransactionConfirmed)
[node.log](https://github.com/user-attachments/files/17433265/node.log)

**Comment by chenyukang** [comment]
please have a verify for this issue, I think it has been fixed.
