### ISSUE TITLE
Payment route-finding does not use complete balance information of owned channels

### ISSUE THREAD

**Issue by contrun** [nervosnetwork/fiber#257]
Currently we are adding only gossip information to the network graph. But for privacy reason, gossip messages do not expose some useful information for routing. For example, some channels' (e.g. those are owned by the local node) states are completely transparent to local node. While finding routes for a payment, we can use this information to avoid some certain failures (sending tlc with balance even higher than our own balance).

**Comment by chenyukang** [comment]
close this issue for #397
