### ISSUE TITLE
How can I identify different senders using keysend in Fiber?

### ISSUE THREAD

**Issue by Flouse** [nervosnetwork/fiber#278]
docs: https://github.com/nervosnetwork/fiber/blob/main/src/rpc/README.md#method-send_payment

## Question
Are there any optional parameters or best practices when using keysend that could help distinguish between different senders?

### Example Inputs for Fiber RPC Method `send_payment`
- target_pubkey
- amount
- custom ID **(not currently supported?)**

**Comment by chenyukang** [comment]
I plan to add `custom_records` for a payment:
https://github.com/chenyukang/fiber/commit/7465e560c6fb4035e046b4118da02de92c958e4d

do you think is it enough?

**Comment by chenyukang** [comment]
- `custom_records` (type: `Option<Vec<(u32, Vec<u8>)>`): Custom records to attach to the payment. The first element of the tuple is the record type, the second element is the base64 encoded bytes.

**Comment by Flouse** [comment]
> * `custom_records` (type: `Option<Vec<(u32, Vec<u8>)>`): Custom records to attach to the payment. The first element of the tuple is the record type, the second element is the base64 encoded bytes.

Looks great!
