### ISSUE TITLE
[upgrade]: Upgrade encountered error

### ISSUE THREAD

**Issue by mfuuzy** [nervosnetwork/fiber#316]
Hi Fiber team, I encountered the following error log when upgrading to the latest version. What could be the issue?

Version:  https://github.com/nervosnetwork/fiber/commit/feefe59ba06731ba3b9881f20a16cdb0c34c3739

The error log is as follows:
```
Error: Exit because failed to load chain spec: Is a directory (os error 21)
  2024-11-18T10:11:52.094341Z  INFO fnn: Starting node with git version feefe59
    at src/main.rs:59
```

**Comment by chenyukang** [comment]
what is the content of your `config.yml` ?

**Comment by mfuuzy** [comment]
Sorry, I wasn't using the latest config file earlier. It's working fine after using the latest config.
