### ISSUE TITLE
[send_payment]  RUSD send failed

### ISSUE THREAD

**Issue by mfuuzy** [nervosnetwork/fiber#319]
Hi Fiber team, I used version [feefe59](https://github.com/nervosnetwork/fiber/commit/feefe59ba06731ba3b9881f20a16cdb0c34c3739) and restarted two nodes, A and B. I opened CKB and RUSD channels. CKB sent successfully, but RUSD failed. I tested with the previous version, and both scenarios worked fine. Below are the detailed conditions:

##  node B new_invoice
```
{
    "id": 42,
    "jsonrpc": "2.0",
    "method": "new_invoice",
    "params": [
        {
            "amount": "0x3e8",
            "currency": "Fibt",
            "description": "node1 to node2",
            "payment_preimage": "0xc98223f6a5693d99637e81d4bb764b4b7042f071aefec72e30923af2043e149d",
            "hash_algorithm": "sha256",
            "udt_type_script": {
                "code_hash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a",
                "hash_type": "type",
                "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b"
            }
        }
    ]
}
```
## node A send_payment
```
{
	"id": 42,
	"jsonrpc": "2.0",
	"method": "send_payment",
	"params": [
		{
			"invoice": "fibt10001ppruqtlsl6vqzg7dwfhdvm6allxx97x7999j89ey74lpyxparrrgkq5smsx0s908uvfp3pzrp73y5zpyaysz4dwg8rcv7q6v20vmjxlcsz56nzzss2u6dw0dkxmdkur9uhdrqmwvsyhrgjn6zem3c84aaluu8vjz9gz8japd34tgukcez9436ax4smshgjq6jkgpt39alfktvau2t52dyexmxwnklfnlex5tw5vde3n8nea2ekmedkpn246fhnvr5kpn48ugy4gqm933ezd4ju44mn7wh2mu7sxp4u94kf607smwplq4kj92lklsjatyhmjjt4l9y5h43wz2jv0tnj2ptca4pwfzv4qcwxy37hxzgdjyc3wsgarqrz2cfc99qxrz02z692qy4p6jpmx7ks5awrk2phe2zjchzgpammxh2m2ylm6x0tcgq6jfz44m072qzfhf7cqsvgmd7"
		}
	]
}
```

### node A 
```
  2024-11-18T12:18:26.070919Z  INFO fnn::fiber::graph: build_route source: Pubkey(PublicKey(29d210971fa3220a4ef267d49f92fe747810c4d4c40b66a14c26f8f93d396d3e7cbf6eb906827264f6e8b27c2087766115f8f20f2baafd670cffdd7c449d1361)) target: Pubkey(PublicKey(0e9442b3a5e6483b50b4aea509058356591f455c0309c837172a8bdb7ff499d185d659409a86612a566ec37073cf1e00f5e54a519f8407535bcfbe5e3ca34ac2)) amount: 1000, payment_hash: Hash256(0xca402d6fda270fbbb5ac4aa461929741f15392499d9d04b8fd718a2ebbdb4128)
    at src/fiber/graph.rs:543
    in ractor::actor::Actor with id: "0.2", name: "Network QmTGtRekmJLA8B3M7RXcNVN4DZzVDhf361b7dgFPNXzhNx"

  2024-11-18T12:18:26.070958Z  INFO fnn::fiber::graph: get_route: nodes visited: 2, edges expanded: 1, time: 12.98µs 
result: [PathEdge { target: Pubkey(PublicKey(0e9442b3a5e6483b50b4aea509058356591f455c0309c837172a8bdb7ff499d185d659409a86612a566ec37073cf1e00f5e54a519f8407535bcfbe5e3ca34ac2)), channel_outpoint: OutPoint(0xf5e2d1dd483e3775ced5894ceb8e7d68f5f9d22af121a066775fd1bef208187600000000) }]
    at src/fiber/graph.rs:800
    in ractor::actor::Actor with id: "0.2", name: "Network QmTGtRekmJLA8B3M7RXcNVN4DZzVDhf361b7dgFPNXzhNx"

```

### node B
```

  2024-11-18T12:18:26.074542Z ERROR fnn::fiber::channel: Error handling AddTlc message: InvalidParameter("Trying to add tlc with id 8 while expecting id 0")
    at src/fiber/channel.rs:499
    in ractor::actor::Actor with id: "0.5"

  2024-11-18T12:18:26.074575Z ERROR fnn::fiber::channel: Error while processing channel message: InvalidParameter("Trying to add tlc with id 8 while expecting id 0")
    at src/fiber/channel.rs:1855
    in ractor::actor::Actor with id: "0.5"

  2024-11-18T12:18:26.075605Z ERROR fnn::fiber::channel: Error while processing channel message: Musig2VerifyError(BadSignature)
    at src/fiber/channel.rs:1855
    in ractor::actor::Actor with id: "0.5"
```

**Comment by chenyukang** [comment]
@contrun seems when there are some errors happened in previous AddTLC (or remove_tlc, I'm not sure), the following AddTlc may got this kind of error:

```console
InvalidParameter("Trying to add tlc with id 8 while expecting id 0")
```

is there anything we need to fix?

similar issue: https://github.com/nervosnetwork/fiber/issues/318

**Comment by chenyukang** [comment]
@mfuuzy 
considering https://github.com/nervosnetwork/fiber/issues/319#issuecomment-2482942084, I think previous error blocked current send_payment, before we fixed it,
could you please have a retry with new fiber database?

**Comment by contrun** [comment]
The problem

> InvalidParameter("Trying to add tlc with id 8 while expecting id 0")

seems to be due to the fact node A changed its next offered tlc ID to 8, while node B was expecting next received tlc ID to be 0. It is hard to guess the reason why these nodes have different tlc IDs from current logs. But while reestablishing channels on re-connection, we should have resent all unconfirmed TLCs.

Currently we lack a rpc method to show all in-flight TLC information. That may help us to debug this problem.

For now, I'd like to know if this problem is 100% reproducible. If so, @mfuuzy can you drop more hints on how you produce the problem? Can we toggle the problem by merely starting a new channel, creating an invoice and then making the payment? Also, if possible, please attach all the state directories (if that is not sensitive) of node A and node B here. These are directories with subdirectory `fiber/store/`.

**Comment by mfuuzy** [comment]
> The problem
> 
> > InvalidParameter("Trying to add tlc with id 8 while expecting id 0")
> 
> seems to be due to the fact node A changed its next offered tlc ID to 8, while node B was expecting next received tlc ID to be 0. It is hard to guess the reason why these nodes have different tlc IDs from current logs. But while reestablishing channels on re-connection, we should have resent all unconfirmed TLCs.
> 
> Currently we lack a rpc method to show all in-flight TLC information. That may help us to debug this problem.
> 
> For now, I'd like to know if this problem is 100% reproducible. If so, @mfuuzy can you drop more hints on how you produce the problem? Can we toggle the problem by merely starting a new channel, creating an invoice and then making the payment? Also, if possible, please attach all the state directories (if that is not sensitive) of node A and node B here. These are directories with subdirectory `fiber/store/`.

I closed the old RUSD channel, reopened a new one, and was then able to successfully send RUSD. Currently, this is in the testing environment. If needed, I can provide the complete fiber files for A and B.
