### ISSUE TITLE
List all optional parameters in the config.yml file

### ISSUE THREAD

**Issue by CipherWang** [nervosnetwork/fiber#343]
When I start a fiber node, I cannot find a spec for config.yml file except for the annotation in the file. However, the annotation covers only a portion of the setups. Many parameters are absent, including **node_name**.  It's better to add more parameters annotation in this file.

**Comment by quake** [comment]
All options' descriptions can be found via `fnn --help` and be overridden by command line arguments or environment variables. For example, you will found this output:
```
--fiber-announced-node-name [<FIBER_ANNOUNCED_NODE_NAME>]    node name to be announced to fiber network [env: FIBER_ANNOUNCED_NODE_NAME=]
```
just run `fnn --fiber-announced-node-name=foo` or add an option to the config file to setup the `node-name`

```
fiber:
  announced_node_name: foo
```
