### ISSUE TITLE
Configuration issue with config.yml

### ISSUE THREAD

**Issue by mfuuzy** [nervosnetwork/fiber#387]
I found that the config file has an additional announced_addrs configuration. If configured as shown [here](https://github.com/nervosnetwork/fiber/blob/e4ca393faa94eef2b46febe895b2e313d43a011c/config/testnet/config.yml#L11), the node_info result is:
```
/ip4/x.x.x.x/tcp/18228/p2p/Qmb7Atjf9zAzoXdR1L4fus4JajuaD6hnNiSkNeeev4Njor/p2p/Qmb7Atjf9zAzoXdR1L4fus4JajuaD6hnNiSkNeeev4Njor
```
However, if you use `/ip4/YOUR-FIBER-NODE-PUBLIC-IP/tcp/8228`, it works correctly.
```
/ip4/x.x.x.x/tcp/18228/p2p/Qmb7Atjf9zAzoXdR1L4fus4JajuaD6hnNiSkNeeev4Njor
```

**Comment by contrun** [comment]
Thanks for reporting. This should be fixed in https://github.com/nervosnetwork/fiber/pull/410. Note that if you specify a peer id in the `announced_addrs` then its peer id must match the real peer id.
