### ISSUE TITLE
Be more resilient to errors in calling the chain rpc service

### ISSUE THREAD

**Issue by contrun** [nervosnetwork/fiber#65]
Currently we always assume that the chain actor is alive. Since the chain actor is dependent on service from outside. We can't really be sure if the outside rpc service is always alive. We must make this more resilient.

This commit makes it more explicitly that which places we made the assumption of chain actor never dies.
https://github.com/contrun/ckb-pcn-node/pull/64/commits/3288571a7d8e1c4379306d2f5e86d311e7886812

- [x] #303 
- [x] Eliminate `expect` in `ckb::funding`: #307
- [x] Eliminate `expect` in `ckb::contracts`
    - [x] #310  
    - [x] #311

**Comment by contrun** [comment]
This issue is not resolved yet. #303 only replaces unwrap with expect.

**Comment by doitian** [comment]
Close for now. Future works depend on user reporting.
