### ISSUE TITLE
Channel state should only be removed when shutdown transaction has been confirmed

### ISSUE THREAD

**Issue by contrun** [nervosnetwork/fiber#86]
Currently channel state is removed immediately after channel state changed to `Closed`. This is undesirable. We need to wait for the shutdown transaction. Also, sometime user may want to keep channel even if it is finished.

https://github.com/nervosnetwork/cfn-node/blob/f9e79b060f7329309eff752b7485bfacc91a629f/src/ckb/channel.rs#L1085

**Comment by eval-exec** [comment]
Hello, @contrun
Can we change the status of this Kanban to `Done` now?

**Comment by contrun** [comment]
Yes. This issue is resolved with https://github.com/nervosnetwork/cfn-node/pull/124
