### ISSUE TITLE
Take transaction fee into consideration while building commitment transaction

### ISSUE THREAD

**Issue by contrun** [nervosnetwork/fiber#87]
https://github.com/nervosnetwork/cfn-node/blob/f9e79b060f7329309eff752b7485bfacc91a629f/src/ckb/channel.rs#L3315

Currently, while building commitment transaction outputs, we didn't consider transaction fee. This will effectively make commitment transaction unbroadcastable.

**Comment by doitian** [comment]
Already done? cc @chenyukang

**Comment by chenyukang** [comment]
Will be done in this PR: https://github.com/nervosnetwork/cfn-node/pull/121
